apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/nithish/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 12 Dec 2024 18:24:55 EST
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://localhost:49493
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 12 Dec 2024 18:24:55 EST
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/nithish/.minikube/profiles/minikube/client.crt
    client-key: /Users/nithish/.minikube/profiles/minikube/client.key
