apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo-app
spec:
  containers:
  - name: mongo
    image: mongo:4.4
    resources:
      requests:
        memory: "100Mi" # extra memeory's limit
      limits:
        memory: "200Mi" # allocated memory 
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
    ports:
      - containerPort: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "root"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "rootpassword"
