apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-app
spec:
  selector:
    app: mongo-app 
  ports:
    - protocol: TCP
      port: 27017     
      targetPort: 27017 
  clusterIP: None     
