apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo-app
spec:
  containers:
  - name: mongo
    image: mongo:4.4
    ports:
      - containerPort: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "root"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "rootpassword"
